import { config } from '@/config'
import type { AgeGroup, Scene } from '@/types'

/**
 * Every prompt in the application, shared by all providers rather than
 * duplicated per adapter.
 *
 * Gemini and Qwen both accept plain instructions, so per-model divergence is
 * speculation until demonstrated. This file is also what
 * `config.content.textVersion` gates — bump that version whenever a change
 * here should regenerate cached content.
 */

const AGE_DESCRIPTIONS: Record<AgeGroup, string> = {
  '4-6': 'a 5-year-old child who is just learning to read',
  '7-10': 'a 9-year-old child who reads independently',
}

/**
 * Sets the role and the vocabulary ceiling for enrichment.
 *
 * The ceiling is explicit because "use simple words" is not reliable — models
 * routinely reach for a harder word when it is more precise. The instruction
 * is to rephrase instead.
 */
export function enrichSystemPrompt(ageGroup: AgeGroup): string {
  const audience = AGE_DESCRIPTIONS[ageGroup]
  const sentences = ageGroup === '4-6' ? 'exactly one short sentence' : 'one or two sentences'

  return `You write dictionary definitions for ${audience}.

Rules:
- Use only words that ${audience} already knows. If you need a harder word to be precise, rephrase instead — never reach for the harder word.
- Write the definition as ${sentences}. The definition must not contain the word being defined.
- Write exactly ${config.word.maxExamples} example sentences. Every example sentence MUST contain the word being defined, spelled exactly as given. The examples are how the child learns to use the word — an example that avoids the word, or replaces it with an easier synonym, is useless and must not be written.
- Each example must show the word doing its job, so that a child who did not read the definition could still guess what it means from the sentence.
- Set every example in a child's own world: home, school, playground, family, animals, food, weather.
- Keep it warm and plain. No jokes that need adult knowledge.

For the word "enormous", these are the shapes to follow and avoid:
GOOD: "The elephant at the zoo was enormous." — uses the word, and the setting hints at the meaning.
BAD: "The dog is so big and tall." — the word never appears, so the child learns nothing.

Respond with JSON only, in this exact shape:
{"definition": "...", "examples": ["...", "..."]}`
}

export function enrichUserPrompt(word: string, rawDefinition: string, ageGroup: AgeGroup): string {
  return `Word: "${word}"
Dictionary definition: "${rawDefinition}"

Rewrite this for ${AGE_DESCRIPTIONS[ageGroup]}.`
}

/**
 * Sets the rules for the comic script.
 *
 * Two constraints carry the pedagogy: the word must appear in the text, and
 * the meaning must be inferable from the scenes alone. A child who cannot
 * read the definition should still understand the word from the pictures.
 */
export function storySystemPrompt(ageGroup: AgeGroup): string {
  const audience = AGE_DESCRIPTIONS[ageGroup]

  return `You write short picture-book stories for ${audience}.

Rules:
- Every scene must use the word naturally in its text. A story that never uses the word teaches nothing.
- The scenes together must make the word's meaning obvious from context alone, without the definition.
- Use the same character in every scene so the panels read as one story.
- One or two short sentences per scene.
- Nothing scary, violent, sad or unsettling. No danger, injury, or characters in distress.
- Describe what can be seen. The scenes become drawings.

Respond with JSON only, in this exact shape:
[{"scene": 1, "text": "..."}, {"scene": 2, "text": "..."}]`
}

export function storyUserPrompt(word: string, sceneCount: number): string {
  return `Write a ${sceneCount}-scene story that teaches the word "${word}".`
}

/**
 * Assembles the image prompt from the script.
 *
 * Built here rather than generated by a model so the style clause and the
 * panel count are identical for every comic in the app. The panel count must
 * be explicit or the model produces an arbitrary number and the picture stops
 * matching the script.
 */
export function buildImagePrompt(scenes: Scene[]): string {
  const panels = scenes
    .map(s => `Panel ${s.scene}: ${s.text}`)
    .join(' ')

  return `A children's comic strip with exactly ${scenes.length} equal-width panels side by side. ` +
    `Flat cartoon illustration, bright cheerful colours, thick clean outlines, simple friendly shapes. ` +
    `The same character appears in every panel. No text, no speech bubbles, no lettering anywhere. ` +
    panels
}

/**
 * Keeps only the examples that actually contain the word.
 *
 * The prompt demands the word verbatim, but models still paraphrase it away
 * ("The dog is so big" for "enormous"), and such a sentence teaches nothing.
 * Matching is case-insensitive and allows a suffix, so "enormously" and
 * "Enormous" both count, while a bare synonym does not.
 */
export function keepExamplesUsingWord(examples: string[], word: string): string[] {
  const stem = word.trim().toLowerCase()
  if (!stem) return []

  const pattern = new RegExp(`\\b${stem.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\w*\\b`, 'i')
  return examples.filter(example => pattern.test(example))
}

/**
 * Extracts JSON from a model response.
 *
 * Models add markdown fences and conversational padding despite being told to
 * return raw JSON, so this falls back to locating the outermost bracket pair.
 * Returns null rather than throwing — the pipeline treats that as a normal
 * degradation, whereas a throw would fail the whole request.
 */
export function parseJsonResponse<T>(raw: string): T | null {
  if (!raw) return null

  const withoutFence = raw
    .replace(/^\s*```(?:json)?\s*/i, '')
    .replace(/\s*```\s*$/, '')
    .trim()

  try {
    return JSON.parse(withoutFence) as T
  } catch {
    // Fall through to bracket extraction.
  }

  const start = withoutFence.search(/[[{]/)
  if (start === -1) return null
  const opener = withoutFence[start]
  const closer = opener === '[' ? ']' : '}'
  const end = withoutFence.lastIndexOf(closer)
  if (end <= start) return null

  try {
    return JSON.parse(withoutFence.slice(start, end + 1)) as T
  } catch {
    return null
  }
}
